#ifndef TASK_CONSTANTS_H
#define TASK_CONSTANTS_H

#define GRIPPER_TASK_DELAY_MS 50U
#define ZAXIS_DEBOUNCE_DELAY_MS 10U
#define CONNECTION_TASK_DELAY_MS 50U
#define XY_AXIS_TASK_DELAY_MS 50U
#define STEPPER_IDLE_DELAY_MS 5U
#define STEPPER_LOOP_DELAY_MS 1U
#define STEPPER_NOTIFY_WAIT_MS 1U
#define SWITCH_DEBOUNCE_DELAY_MS 50U
#define SERVO_TASK_DELAY_MS 100U
#define UART_TASK_DELAY_MS 10U

#endif
